### ISSUE TITLE
Typo in the website

### ISSUE THREAD

**Issue by akshika47** [ggjy/ggjy.github.io#1]
Hi @ggjy,

I saw that there is a typo on your website. The word 'Detection' has been misspelt I think. If it was intentional, please ignore this issue. :) 

<img width="738" alt="image" src="https://user-images.githubusercontent.com/4003135/210225158-c1d2aaef-762e-4412-91f7-6a215118fcee.png">

**Comment by ggjy** [comment]
Thanks for pointing out that!

**Comment by akshika47** [comment]
Not a problem ;)
